### ISSUE TITLE
GPU/CPU parallelization

### ISSUE THREAD

**Issue by navamikairanda** [williamljb/DifferentiableCloth#6]
Hello, 

Thanks for sharing this project and releasing the code. This is really cool work!

In demo_{}.py examples, I noticed that PyTorch threads are set for CPU parallelization using torch.set_num_threads(8). However, I fail to see any performance speed-up/degradation when the number of threads is varied (I tried with num_threads = 1, 2, 4, 8). I am running against a server with 64 physical (or 256 logical) CPUs available. Are the forward and backward pass both expected to benefit from multi-threading (say 8 cpu vs. 1 cpu)?

On another note, is CUDA used in the project or experimental? All the tensors seem to be loaded in CPU device, it's not clear to me if GPUs are actually leveraged in C++/PyTorch parts of the source code. 
 
I am working with high resolution meshes, so looking for ways to train the experiments as faster as possible.

**Comment by williamljb** [comment]
Hi navamikairanda,

1: CPU parallelization is enabled only for collision detection [here](https://github.com/williamljb/DifferentiableCloth/blob/master/arcsim/src/collision.cpp#L253). The current bottleneck is the dealing with the potentially collided face pairs [here](https://github.com/williamljb/DifferentiableCloth/blob/master/arcsim/src/collision.cpp#L260). I failed to parallelize it because there is one substep inside that calls back to Python [here](https://github.com/williamljb/DifferentiableCloth/blob/master/arcsim/src/collision.cpp#L311). It seems that if multiple callbacks from different threads arrive to the python module [here](https://github.com/williamljb/DifferentiableCloth/blob/master/pysim/util_py.py), it will cause a segmentation fault. I don't currently have any solution on this. That said, the current code is not fully parallelizable.

2: The code does not currently support GPU, since it needs an open-source GPU-based cloth simulation.

**Comment by navamikairanda** [comment]
That's helpful, thank you - Navami
